-- 政采云完整类目数据（最终版）
-- 数据来源：合并数据（旧数据 + 新提取）
-- 总计：208个类目
-- 一级：78 | 二级：36 | 三级：94
-- 生成时间：2025-11-29T03:13:52.171Z

DELETE FROM zcy_categories;

-- 一级类目 (78个)
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (2136, '2136', '橡胶及塑料制品', 1, NULL, 1, 0, 1, 1);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4402, '4402', '文化用品', 1, NULL, 1, 0, 1, 2);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4410, '4410', '文化玩乐', 1, NULL, 1, 0, 1, 3);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4401, '4401', '办公设备/耗材', 1, NULL, 1, 0, 0, 4);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4426, '4426', '办公设备', 1, NULL, 1, 0, 0, 5);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4427, '4427', '办公用纸', 1, NULL, 1, 0, 0, 6);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4428, '4428', '打印机及配件', 1, NULL, 1, 0, 0, 7);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4429, '4429', '传真/通信设备', 1, NULL, 1, 0, 0, 8);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4430, '4430', '投影机及配件', 1, NULL, 1, 0, 0, 9);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4431, '4431', '点/验钞/收款机及配件', 1, NULL, 1, 0, 0, 10);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4432, '4432', '条码扫描/采集器材', 1, NULL, 1, 0, 0, 11);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4433, '4433', '磁盘刻录及存储设备', 1, NULL, 1, 0, 0, 12);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4434, '4434', '其它办公设备及配件', 1, NULL, 1, 0, 0, 13);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4435, '4435', '墨粉/硒鼓/油墨', 1, NULL, 1, 0, 0, 14);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4436, '4436', '绳索/扎带/办公线材/胶带', 1, NULL, 1, 0, 0, 15);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4437, '4437', '包装设备/标牌及耗材', 1, NULL, 1, 0, 0, 16);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4438, '4438', '会议/教室/展示', 1, NULL, 1, 0, 0, 17);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (4439, '4439', '门禁考勤器材', 1, NULL, 1, 0, 0, 18);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (1102102, '1102102', '打印机配件', 1, NULL, 1, 0, 0, 19);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5177, '5177', '双面胶带', 1, NULL, 0, 1, 0, 20);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5178, '5178', '海绵胶带', 1, NULL, 0, 0, 0, 21);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5179, '5179', '玻璃布胶带', 1, NULL, 0, 0, 0, 22);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5180, '5180', '工业胶带', 1, NULL, 0, 0, 0, 23);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5181, '5181', '牛皮纸胶带', 1, NULL, 0, 0, 0, 24);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5182, '5182', '纤维胶带', 1, NULL, 0, 0, 0, 25);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5183, '5183', '行李绳', 1, NULL, 0, 0, 0, 26);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5184, '5184', 'bopp胶带', 1, NULL, 0, 0, 0, 27);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5185, '5185', 'opp胶带', 1, NULL, 0, 0, 0, 28);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5186, '5186', 'pet胶带', 1, NULL, 0, 0, 0, 29);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5187, '5187', 'pe胶带', 1, NULL, 0, 0, 0, 30);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5188, '5188', 'pvc胶带', 1, NULL, 0, 1, 0, 31);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5189, '5189', '布胶带', 1, NULL, 0, 0, 0, 32);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5190, '5190', '沥青胶带', 1, NULL, 0, 0, 0, 33);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5191, '5191', '铝箔胶带', 1, NULL, 0, 0, 0, 34);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5192, '5192', '玛拉胶带', 1, NULL, 0, 0, 0, 35);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5193, '5193', '美纹纸胶带', 1, NULL, 0, 0, 0, 36);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5194, '5194', '特氟龙胶带', 1, NULL, 0, 0, 0, 37);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5195, '5195', '办公线材', 1, NULL, 0, 0, 0, 38);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5196, '5196', '结束带', 1, NULL, 0, 0, 0, 39);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5151, '5151', '网络配件', 1, NULL, 0, 0, 0, 40);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5152, '5152', '复印机配件', 1, NULL, 0, 0, 0, 41);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5153, '5153', '网络盒子', 1, NULL, 0, 1, 0, 42);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5154, '5154', '标价机', 1, NULL, 0, 1, 0, 43);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5156, '5156', '扫描仪配件', 1, NULL, 0, 0, 0, 44);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5157, '5157', '刻字机配件', 1, NULL, 0, 0, 0, 45);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5158, '5158', '幻灯机配件', 1, NULL, 0, 0, 0, 46);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5159, '5159', '3D打印机耗材', 1, NULL, 0, 1, 0, 47);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5160, '5160', '标签机配件', 1, NULL, 0, 0, 0, 48);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5136, '5136', '点钞机', 1, NULL, 0, 1, 0, 49);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5137, '5137', '点钞机配件', 1, NULL, 0, 0, 0, 50);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5138, '5138', '收款机', 1, NULL, 0, 1, 0, 51);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5139, '5139', '收款机配件', 1, NULL, 0, 0, 0, 52);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5140, '5140', '验钞机/笔', 1, NULL, 0, 1, 0, 53);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5015, '5015', '碎纸机', 1, NULL, 0, 1, 0, 54);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5016, '5016', '碎纸机配件', 1, NULL, 0, 0, 0, 55);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5017, '5017', '扫描仪', 1, NULL, 0, 1, 0, 56);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5018, '5018', '复印机', 1, NULL, 0, 1, 0, 57);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5019, '5019', '保险箱/柜', 1, NULL, 0, 1, 0, 58);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5020, '5020', '保管箱', 1, NULL, 0, 1, 0, 59);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5021, '5021', '切纸机', 1, NULL, 0, 1, 0, 60);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5022, '5022', '多功能一体机配件', 1, NULL, 0, 1, 0, 61);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5023, '5023', '彩色激光多功能一体机', 1, NULL, 0, 1, 0, 62);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5024, '5024', '其它多功能一体机', 1, NULL, 0, 1, 0, 63);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5025, '5025', '触控一体机', 1, NULL, 0, 1, 0, 64);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5026, '5026', '黑白激光多功能一体机', 1, NULL, 0, 1, 0, 65);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5027, '5027', '墨仓式多功能一体机', 1, NULL, 0, 1, 0, 66);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5028, '5028', '喷墨多功能一体机', 1, NULL, 0, 1, 0, 67);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5029, '5029', '打字机/配件', 1, NULL, 0, 0, 0, 68);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5030, '5030', '绘图仪', 1, NULL, 0, 1, 0, 69);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5032, '5032', '销毁设备', 1, NULL, 0, 0, 0, 70);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5033, '5033', '光标阅卷机', 1, NULL, 0, 1, 0, 71);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5034, '5034', '刻字机', 1, NULL, 0, 1, 0, 72);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5035, '5035', '冷裱机', 1, NULL, 0, 1, 0, 73);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5036, '5036', '一体化速印机', 1, NULL, 0, 1, 0, 74);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5037, '5037', '幻灯机', 1, NULL, 0, 1, 0, 75);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (5038, '5038', '办税终端机', 1, NULL, 0, 1, 0, 76);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (12670, '12670', '高拍仪', 1, NULL, 0, 1, 0, 77);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children,has_spu, authed, sort_order) VALUES (1101184, '1101184', '手机屏蔽柜', 1, NULL, 0, 0, 0, 78);

-- 二级类目 (36个)
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2137, '2137', '橡胶带', 2, 2136, 1, 0, 1, 1);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2143, '2143', '橡胶板', 2, 2136, 1, 0, 1, 2);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2156, '2156', '塑料片', 2, 2136, 1, 0, 1, 3);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2166, '2166', '塑料管', 2, 2136, 1, 0, 1, 4);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2180, '2180', '橡胶管', 2, 2136, 1, 0, 1, 5);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2197, '2197', '其他橡胶塑料制品', 2, 2136, 1, 0, 1, 6);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4440, '4440', '笔类/书写工具', 2, 4402, 1, 0, 1, 7);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4441, '4441', '纸张本册', 2, 4402, 1, 0, 1, 8);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4442, '4442', '财会用品', 2, 4402, 1, 0, 1, 9);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4443, '4443', '收纳/陈列用品', 2, 4402, 1, 0, 1, 10);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4444, '4444', '装订用品', 2, 4402, 1, 0, 1, 11);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4445, '4445', '刀剪/粘胶/测绘', 2, 4402, 1, 0, 1, 12);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4446, '4446', '日常学习用品', 2, 4402, 1, 0, 1, 13);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4447, '4447', '画具/画材/书法用品', 2, 4402, 1, 0, 1, 14);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4448, '4448', '其它办公用品', 2, 4402, 1, 0, 1, 15);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4449, '4449', '印刷制品', 2, 4402, 1, 0, 1, 16);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4450, '4450', '教学用具', 2, 4402, 1, 0, 1, 17);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4451, '4451', '实验室用品', 2, 4402, 1, 0, 1, 18);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4452, '4452', '电子产品及配件', 2, 4402, 1, 0, 1, 19);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4453, '4453', '期刊/资料/档案', 2, 4402, 1, 0, 1, 20);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4454, '4454', '图书/档案设备', 2, 4402, 1, 0, 1, 21);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4604, '4604', '书籍/杂志/报纸', 2, 4410, 1, 0, 1, 22);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4605, '4605', '钢琴及配件', 2, 4410, 1, 0, 1, 23);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4607, '4607', '吉他及配件', 2, 4410, 1, 0, 1, 24);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4608, '4608', '提琴及配件', 2, 4410, 1, 0, 1, 25);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4609, '4609', '西洋乐器', 2, 4410, 1, 0, 1, 26);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4610, '4610', '民族乐器', 2, 4410, 1, 0, 1, 27);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4611, '4611', '乐器配件', 2, 4410, 1, 0, 1, 28);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4612, '4612', '锣', 2, 4410, 1, 0, 1, 29);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4613, '4613', '鼓', 2, 4410, 1, 0, 1, 30);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4614, '4614', '儿童玩具乐器', 2, 4410, 1, 0, 1, 31);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4615, '4615', '乐器音箱', 2, 4410, 1, 0, 1, 32);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4616, '4616', '模玩/动漫/周边/cos/桌游', 2, 4410, 1, 0, 1, 33);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4617, '4617', 'MIDI乐器/电脑音乐', 2, 4410, 1, 0, 1, 34);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (4618, '4618', '古董/邮币/字画/收藏', 2, 4410, 1, 0, 1, 35);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5197, '42kjwzej34', '束线带', 2, 4436, 0, 0, 1, 36);

-- 三级类目 (94个)
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2138, '2138', '橡胶止水带', 3, 2137, 0, 0, 1, 1);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2139, '2139', '橡胶传送带', 3, 2137, 0, 0, 1, 2);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2140, '2140', '橡胶捆绑带', 3, 2137, 0, 0, 1, 3);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2141, '2141', '橡胶履带', 3, 2137, 0, 0, 1, 4);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2144, '2144', '夹布胶板', 3, 2143, 0, 0, 1, 5);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2145, '2145', '绝缘胶板', 3, 2143, 0, 0, 1, 6);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2146, '2146', '耐油胶板', 3, 2143, 0, 0, 1, 7);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2147, '2147', '耐酸碱胶板', 3, 2143, 0, 0, 1, 8);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2148, '2148', '防腐衬里', 3, 2143, 0, 0, 1, 9);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2149, '2149', '阻尼胶板', 3, 2143, 0, 0, 1, 10);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2150, '2150', '防滑胶板', 3, 2143, 0, 0, 1, 11);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2151, '2151', '防腐胶板', 3, 2143, 0, 0, 1, 12);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2152, '2152', '耐磨胶板', 3, 2143, 0, 0, 1, 13);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2153, '2153', '防静电胶板', 3, 2143, 0, 0, 1, 14);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2154, '2154', '特种橡胶板', 3, 2143, 0, 0, 1, 15);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2157, '2157', 'PP塑料片', 3, 2156, 0, 0, 1, 16);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2158, '2158', 'PE塑料片', 3, 2156, 0, 0, 1, 17);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2159, '2159', 'PET塑料片', 3, 2156, 0, 0, 1, 18);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2160, '2160', 'ABS塑料片', 3, 2156, 0, 0, 1, 19);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2161, '2161', 'PMMA塑料片', 3, 2156, 0, 0, 1, 20);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2162, '2162', 'PC塑料片', 3, 2156, 0, 0, 1, 21);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2163, '2163', 'PS塑料片', 3, 2156, 0, 0, 1, 22);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2165, '2165', 'PVC塑料片', 3, 2156, 0, 0, 1, 23);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2167, '2167', 'PVC管', 3, 2166, 0, 0, 1, 24);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2168, '2168', 'PPR管', 3, 2166, 0, 0, 1, 25);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2169, '2169', 'PP管', 3, 2166, 0, 0, 1, 26);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2170, '2170', 'PE管', 3, 2166, 0, 0, 1, 27);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2171, '2171', 'PC管', 3, 2166, 0, 0, 1, 28);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2172, '2172', 'ABS管', 3, 2166, 0, 0, 1, 29);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2173, '2173', 'PMMA管', 3, 2166, 0, 0, 1, 30);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2174, '2174', '铝塑管', 3, 2166, 0, 0, 1, 31);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2175, '2175', '波纹管', 3, 2166, 0, 0, 1, 32);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2176, '2176', 'PA管', 3, 2166, 0, 0, 1, 33);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2177, '2177', 'PU管', 3, 2166, 0, 0, 1, 34);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2179, '2179', '钢塑管', 3, 2166, 0, 0, 1, 35);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2181, '2181', '低压橡胶管', 3, 2180, 0, 0, 1, 36);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2182, '2182', '高压橡胶管', 3, 2180, 0, 0, 1, 37);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2183, '2183', '硅胶管', 3, 2180, 0, 0, 1, 38);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2184, '2184', '伸缩胶管', 3, 2180, 0, 0, 1, 39);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2185, '2185', '编织胶管', 3, 2180, 0, 0, 1, 40);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2186, '2186', '缠绕胶管', 3, 2180, 0, 0, 1, 41);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2187, '2187', '夹布胶管', 3, 2180, 0, 0, 1, 42);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2188, '2188', '增强软管', 3, 2180, 0, 0, 1, 43);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2189, '2189', '复合胶管', 3, 2180, 0, 0, 1, 44);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2190, '2190', '液压胶管', 3, 2180, 0, 0, 1, 45);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2191, '2191', '喷砂胶管', 3, 2180, 0, 0, 1, 46);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2192, '2192', '耐油胶管', 3, 2180, 0, 0, 1, 47);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2193, '2193', '纤维胶管', 3, 2180, 0, 0, 1, 48);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2194, '2194', '特种胶管', 3, 2180, 0, 0, 1, 49);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2195, '2195', '胶管接头', 3, 2180, 0, 0, 1, 50);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2198, '2198', '涂胶纺织物', 3, 2197, 0, 0, 1, 51);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2199, '2199', '日用及医疗橡胶制品', 3, 2197, 0, 0, 1, 52);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2200, '2200', '泡沫塑料', 3, 2197, 0, 0, 1, 53);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2201, '2201', '塑料网', 3, 2197, 0, 0, 1, 54);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2202, '2202', '塑料绳', 3, 2197, 0, 0, 1, 55);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2203, '2203', '塑料建材', 3, 2197, 0, 0, 1, 56);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2204, '2204', '橡胶棒', 3, 2197, 0, 0, 1, 57);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (2205, '2205', '橡胶片', 3, 2197, 0, 0, 1, 58);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5225, '5225', '中性笔', 3, 4440, 0, 0, 1, 59);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5226, '5226', '替芯/铅芯', 3, 4440, 0, 0, 1, 60);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5227, '5227', '铅笔', 3, 4440, 0, 0, 1, 61);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5228, '5228', '钢笔', 3, 4440, 0, 0, 1, 62);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5229, '5229', '笔用墨水/补充液/墨囊', 3, 4440, 0, 0, 1, 63);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5230, '5230', '圆珠笔', 3, 4440, 0, 0, 1, 64);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5231, '5231', '宝珠/走珠/签字笔', 3, 4440, 0, 0, 1, 65);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5232, '5232', '荧光笔', 3, 4440, 0, 0, 1, 66);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5233, '5233', '油漆笔', 3, 4440, 0, 0, 1, 67);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5235, '5235', '马克笔', 3, 4440, 0, 0, 1, 68);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5236, '5236', '针管笔', 3, 4440, 0, 0, 1, 69);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5237, '5237', '泡泡笔', 3, 4440, 0, 0, 1, 70);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5238, '5238', '正姿笔', 3, 4440, 0, 0, 1, 71);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5239, '5239', 'PU/PVC笔记本', 3, 4441, 0, 1, 1, 72);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5240, '5240', '学生用笔记本', 3, 4441, 0, 1, 1, 73);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5241, '5241', '记事本', 3, 4441, 0, 1, 1, 74);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5242, '5242', '便签本/便条纸/N次贴', 3, 4441, 0, 1, 1, 75);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5243, '5243', '胶装本', 3, 4441, 0, 1, 1, 76);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5244, '5244', '分页纸/索引纸', 3, 4441, 0, 1, 1, 77);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5245, '5245', '螺旋本', 3, 4441, 0, 0, 1, 78);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5246, '5246', '不干胶标签', 3, 4441, 0, 0, 1, 79);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5247, '5247', '硬面抄', 3, 4441, 0, 1, 1, 80);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5248, '5248', '奖状/证书', 3, 4441, 0, 1, 1, 81);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5249, '5249', '同学录/纪念册', 3, 4441, 0, 0, 1, 82);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5250, '5250', '拍纸本', 3, 4441, 0, 1, 1, 83);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5251, '5251', '信纸', 3, 4441, 0, 1, 1, 84);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5252, '5252', '万用手册', 3, 4441, 0, 0, 1, 85);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5253, '5253', '课业本/教学用本', 3, 4441, 0, 0, 1, 86);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5254, '5254', '日记本', 3, 4441, 0, 1, 1, 87);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5255, '5255', '活页替芯', 3, 4441, 0, 0, 1, 88);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5256, '5256', '磁性贴', 3, 4441, 0, 0, 1, 89);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5257, '5257', '贴纸', 3, 4441, 0, 0, 1, 90);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5258, '5258', '折纸/手工纸', 3, 4441, 0, 0, 1, 91);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5259, '5259', '通讯录/电话本', 3, 4441, 0, 0, 1, 92);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5260, '5260', '书签', 3, 4441, 0, 0, 1, 93);
INSERT INTO zcy_categories (id, category_code, name, level, parent_id, has_children, has_spu, authed, sort_order) VALUES (5261, '5261', 'POP广告纸/爆炸贴', 3, 4441, 0, 0, 1, 94);

COMMIT;
