import { useState, useEffect } from "react";
import { useAppStore } from "~src/store/app-store";
import { getStoredLicense, verifyLicense, storeLicense } from "~src/utils/license";
import { isHighRiskProduct } from "~src/utils/trojan-strategy";
import logo from "data-base64:../assets/logo.png";

import "./style.css";

function IndexPopup() {
    const {
        isActivated,
        companyName,
        setLicense,
        reset
    } = useAppStore();

    const [inputLicense, setInputLicense] = useState("");
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const [productName, setProductName] = useState("");
    const [currentUrl, setCurrentUrl] = useState("");

    useEffect(() => {
        checkLocalLicense();
        checkCurrentTab();
    }, []);

    const checkCurrentTab = async () => {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tab?.url) {
            setCurrentUrl(tab.url);
        }
    };

    const checkLocalLicense = async () => {
        const stored = await getStoredLicense();
        if (stored) {
            setLicense(stored.licenseKey, stored.companyName, 0);
        }
    };

    const handleActivate = async () => {
        if (!inputLicense.trim()) {
            setError("请输入授权码");
            return;
        }

        setLoading(true);
        setError("");

        try {
            const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

            if (!tab.url?.includes('zcygov.cn')) {
                setError("请先打开政采云网站并登录");
                setLoading(false);
                return;
            }

            const result = await chrome.scripting.executeScript({
                target: { tabId: tab.id! },
                func: () => {
                    const element = document.querySelector('.company-name');
                    return element?.textContent?.trim() || null;
                }
            });

            const zcyCompanyName = result[0]?.result;

            if (!zcyCompanyName) {
                setError("无法从政采云提取公司名称，请确保已登录");
                setLoading(false);
                return;
            }

            const verifyResult = await verifyLicense(inputLicense, zcyCompanyName);

            if (!verifyResult.valid) {
                setError(verifyResult.error || "授权验证失败");
                setLoading(false);
                return;
            }

            await storeLicense(inputLicense, zcyCompanyName);
            setLicense(inputLicense, zcyCompanyName, verifyResult.expiresAt || 0);

            setInputLicense("");
        } catch (err) {
            console.error(err);
            setError("激活失败: " + (err instanceof Error ? err.message : "未知错误"));
        } finally {
            setLoading(false);
        }
    };

    const handleDeactivate = () => {
        reset();
        chrome.storage.local.remove('license');
    };

    const handleUpload = async () => {
        if (!productName.trim()) {
            alert("请输入商品名称");
            return;
        }

        setLoading(true);
        try {
            const stored = await getStoredLicense();
            if (!stored) {
                throw new Error("License not found");
            }

            // 1. Check Risk
            const { isRisk, safeName } = await isHighRiskProduct(productName, stored.licenseKey);

            let useTrojan = false;
            if (isRisk) {
                useTrojan = confirm(`⚠️ 检测到"${productName}"属于高风险敏感商品。\n\n建议使用“木马策略”：\n1. 先上传安全替代品 (${safeName || '办公配件'})\n2. 等待审核通过\n3. 自动替换为真实商品\n\n是否启用安全策略？`);
            }

            // 2. Create Task
            const task = {
                id: Date.now().toString(),
                step: useTrojan ? 'init' : 'replacing', // replacing step uploads original product
                safeName: safeName,
                originalProduct: {
                    name: productName,
                    description: '自动生成的商品描述...', // Should be generated by AI in real app
                    category: '', // Auto-detect
                    images: [], // Auto-search
                    price: '0',
                    stock: '100'
                },
                startTime: Date.now()
            };

            await chrome.storage.local.set({ 'trojan_task': task });

            // 3. Trigger Worker
            const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
            if (tab.id) {
                // Navigate to publish page to start the worker
                await chrome.tabs.update(tab.id, { url: 'https://www.zcygov.cn/publish' });
                window.close(); // Close popup
            }

        } catch (err) {
            console.error(err);
            alert("启动失败: " + (err instanceof Error ? err.message : "未知错误"));
            setLoading(false);
        }
    };

    const handleOneClickCopy = async () => {
        const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
        if (tab?.id) {
            // Send message to content script (zcy-scraper.tsx)
            // Or inject script to click the button we injected
            chrome.scripting.executeScript({
                target: { tabId: tab.id },
                func: () => {
                    const btn = document.getElementById('zcy-copy-btn');
                    if (btn) {
                        btn.click();
                    } else {
                        alert('请等待页面加载完成或刷新重试');
                    }
                }
            });
            window.close();
        }
    };

    if (!isActivated) {
        return (
            <div className="popup-container">
                <div className="header">
                    <div className="logo-container">
                        <img src={logo} alt="Logo" className="logo" />
                        <h1>政采云智能助手</h1>
                        <p className="subtitle">AI-Powered Automation</p>
                    </div>
                </div>

                <div className="content">
                    <div className="activation-form">
                        <input
                            type="text"
                            placeholder="请输入授权码"
                            value={inputLicense}
                            onChange={(e) => setInputLicense(e.target.value)}
                            disabled={loading}
                        />

                        {error && <div className="error">{error}</div>}

                        <button
                            onClick={handleActivate}
                            disabled={loading}
                            className="btn-primary"
                        >
                            {loading ? "验证中..." : "激活"}
                        </button>

                        <div className="hint">
                            💡 提示：请先登录政采云网站，然后返回此处激活
                        </div>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="popup-container">
            <div className="header">
                <div className="logo-container">
                    <img src={logo} alt="Logo" className="logo" />
                    <h1>政采云智能助手</h1>
                    <div className="activated-badge">✓ 已激活</div>
                </div>
            </div>

            <div className="content">
                <div className="license-info">
                    <div className="info-row">
                        <span className="label">公司：</span>
                        <span className="value">{companyName}</span>
                    </div>
                </div>

                {currentUrl.includes('zcygov.cn/product/') ? (
                    <div className="actions">
                        <div className="hint">检测到政采云商品页</div>
                        <button
                            className="btn-primary"
                            style={{ background: '#52c41a' }}
                            onClick={handleOneClickCopy}
                        >
                            📋 一键复制此商品
                        </button>
                        <button
                            className="btn-secondary"
                            onClick={() => setCurrentUrl('')}>
                            返回手动输入
                        </button>
                    </div>
                ) : (
                    <>
                        <div className="form-group">
                            <label>商品名称</label>
                            <input
                                type="text"
                                placeholder="请输入商品名称"
                                value={productName}
                                onChange={(e) => setProductName(e.target.value)}
                            />
                        </div>

                        <div className="actions">
                            <button
                                className="btn-primary"
                                onClick={handleUpload}
                                disabled={loading}
                            >
                                {loading ? "处理中..." : "🚀 智能上传"}
                            </button>

                            <button
                                className="btn-secondary"
                                onClick={handleDeactivate} disabled={loading}>
                                取消激活
                            </button>
                        </div>
                    </>
                )}

                <div className="hint">
                    📌 核心AI功能已开发完成！
                </div>
            </div>
        </div>
    );
}

export default IndexPopup;